### ISSUE TITLE
Locked fps of animation

### ISSUE THREAD

**Issue by marteach** [svgdotjs/svg.js#1003]
Hi

Is it possible to select at which frame rate an animation should run (calls to renderAnimationFrame)? 

At the moment i have a quite big SVG image with some (around 40) of the elements animating "stroke-dashoffset". The CPU usage is quite high and fps not stable.

Been playing along with the animation outside svg.js and gotten good results (low CPU usage and about the same user experience) by limiting the work in "renderAnimationFrame" calls to every other/ every third and then adjusting the "pixel jump". 

Example of what i mean:

`let aniframe = requestAnimationFrame(animate); 

let framCount = 0; 

let offset = 1; 

function animate() { 
        if (++framCount % 3 == 0) { 
          offset+=3; FLOW_ELEMENTS.forEach(el => el.setAttribute('stroke-dashoffset', offset++)); 
     } 
     aniframe = requestAnimationFrame(animate); 
}`

Since our app also does a lot of other heavy calculations less stress on CPU would be nice (have some free fames). Since the component uses svg.js for other stuff as well it would be nice to be enable to do the suggested without having to swap. 

On the API part guessing as an option to animate:
.animate({duration: 400, ease: '-', skipFrames: 2}).loop();

This might already possible somehow?

**Comment by Fuzzyma** [comment]
No it is not possible. We ate just calling request animation frame which tries to fit a 60 frames per second rate.

However I see that you still use version 2.x. We improved the animation module by a lot! (we never measured the actual speedup but it's huge).
You might want to give it a try. Maybe your problems are solved already at that point.

To your suggestion to adding it: it's not that easy because when you skip a frame, the next frame is never scheduled. It would need some workaround and a second Queue for delayed frames. That might possibly decrease the performance for animations without skipped frames so we have to be careful here!

**Comment by saivan** [comment]
Actually, in theory it is possible to do manually. You could always use `setTimeout` and call `step` on a paused animation yourself. But this is not performant at all. Let me know if you need anymore help here :)
