### ISSUE TITLE
Typescript v3.0.12 

### ISSUE THREAD

**Issue by itsezc** [svgdotjs/svg.js#1009]
# Bug report

Typescript definitions are invalid as of version 3.0.12

## Explanation

- What is the behaviour you expect?
Types to work

- What is happening instead?
VS Code throws an error

- What error message are you getting?
`Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("@svgdotjs/svg.js")' has no compatible call signatures.ts(2349)`

**Comment by Fuzzyma** [comment]
I am not familiar with typescript errors but what's the expression which lags a signature? Also: can you try the current master and see if that works?

**Comment by bart84** [comment]
Hello, I am getting that error also. I am unable to use your library because of that. I am describing the problem in brief the here:

https://stackoverflow.com/questions/58221022/how-to-properly-import-svg-js-3-0-x-version-into-a-typescript-create-react-app-p

Is there a chance of fixing that any time soon?

P.S. I got the newest typings installed with the Svg.js 3.0.13 version. Still can't use your library :(

**Comment by Fuzzyma** [comment]
When you import the library like this: `import * as SVG from "@svgdotjs/svg.js"`, you put all named exports into the SVG variable. However, this object is not a function so you cannot call it.
When you cant to call `SVG()` you actually need to call `SVG.SVG()`. Thats why named imports are much prefered here: `import {SVG} from "@svgdotjs/svg.js"`.
I **think** that should fix the problem here

**Comment by Fuzzyma** [comment]
At the moment of writing I use typescript and its working. So I assume this issue is resolved
