### ISSUE TITLE
SVG(...).size

### ISSUE THREAD

**Issue by mohammad-rajaei-jm** [svgdotjs/svg.js#1022]
Hey man 
In Svgjs v3.0.10 there isn't size method?!!!!!
I couldn't make any svg element!
I try your demo codes in this version and they didn't work too
Please don't waste our time

**Comment by Fuzzyma** [comment]
If you think that way about open source feel free to write your own code and never come back. There are enough issues which relate to your problem and show solutions. A look into the tests would also give you hints.
So stop wasting OUR time writing such issues!

**Comment by mohammad-rajaei-jm** [comment]
Excuse me but That's funny. 
Release a new version and change methods without update Docs!
I love your library and didn't sleep all night to learn it and it didn't work with its doc
I think you should understand me

**Comment by notchris** [comment]
Yeah but @Fuzzyma didn't have to make this library at all. He probably did it because he was passionate about helping people, it got popular, and then the workload became too much to realistically balance with his day-to-day. Either way, there are many improvements being made, probably not as frequent as they were, but at least he responds even.
