### ISSUE TITLE
Support on StackOverflow

### ISSUE THREAD

**Issue by guettli** [svgdotjs/svg.js#1053]
# Feature request

You tell the user to ask for support on Stackoverflow:

> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js)**.

BUT: nobody is there who answers questions there.

The last 6 questions don't got an answer.

It would be very kind (and improve the success for your lib) if you would answer questions at Stackoverflow.

**Comment by Fuzzyma** [comment]
I usually get a mail when a question for the svg.js was added. Ofc that can take a day or two.
I also sometimes only comment on the question because its not clear what was asked.
Beside that, this here is usually a one man show. So please keep that in mind when you ask for support. On stackoverflow there is at least the chance that someone else can help you

**Comment by guettli** [comment]
It is sad that it is a one man show.

Do you want it to be like this?

What does your dream look like?

Why not tell us your dream. Maybe someone with free spare time wants to join?

**Comment by saivan** [comment]
Well, there are two of us working on it now. But neither of us have too much time on our hands :) But we always welcome pull requests to both the documentation and the codebase if you'd like to help out. The more people the merrier. Since this isn't an issue with the library though, is it fine to close it?

**Comment by guettli** [comment]
If I were you, I would state above comment ("Well, there are two of us working on it now. But neither ..") and ask for help on the top of the README. Maybe a talented teenager steps in. But yes, it can be closed. I'll do it.

**Comment by saivan** [comment]
I appreciate it :)
