### ISSUE TITLE
 Svg.js 4: Webassembly core

### ISSUE THREAD

**Issue by janmaslik** [svgdotjs/svg.js#1075]
i think that remake core of this library in webassembly would be big step forward.  Since webassembly is more and more supported and its also designed to improve speed of math functions. It also should reduce size of the library.
What do you think ?

**Comment by Fuzzyma** [comment]
Interesting idea. However, by far the most of the code is dom manipulation and there is no dom for webassembly yet. Furthermore my prefered language is actually javascript :D. Also: We loose a ton of compatibility to older browsers.
Will close this for now because its not feasable at this point of time.

Feel free to try it out. I am very interested in seeing the outcome!
