### ISSUE TITLE
ID for element is undefined

### ISSUE THREAD

**Issue by pzhaojohnson** [svgdotjs/svg.js#1087]
# ID for element is undefined

According to [a previous thread](https://github.com/svgdotjs/svg.js/issues/246), every element should be created with a unique ID, but it seems like an element is not given an ID until the `id` method is called:

```
let text = svg.text('asdf');
text.attr('id'); // gives undefined
text.id(); // gives an actual ID
text.attr('id'); // now gives the same ID as text.id()
```

Is this the intended behavior?

Thanks!

**Comment by Fuzzyma** [comment]
Yes it is. The thread you found is 6 years old. Issues were raised that all this ids are cluttering the svg and I agree. So we only create an id if needed. That shouldnt be a problem since you either set the id or it is created while getting it. Just dont use `attr()` to access the id or make sure that you call id after construction of elements
