### ISSUE TITLE
SVGs id's not creating in the element

### ISSUE THREAD

**Issue by ezra2310** [svgdotjs/svg.js#1103]
We noticed, SVGs id not creating in the element in sample here and it was not created in my project also.
Can anyone help me , How to add ids in all SVG element created by SVG.js library ...
i'm strucked here, any configuarte need to do or What ??? pls suggest
https://jsfiddle.net/Fuzzy/nc15b2tg/?utm_source=website&utm_medium=embed&utm_campaign=nc15b2tg

If anybody gets idea pls share.. How to auto create ids for all SVG.js created element automatically. If i do my manually it might take lot of time to assign the ids.
![SVG](https://user-images.githubusercontent.com/35021500/80096053-8d950480-859b-11ea-964c-15948f9b875e.png)

find the attached file for reference

**Comment by Fuzzyma** [comment]
Please dont open the same issue in different repositories!

If you want an id, just call `id()` and it will be created. This is done to avoid cluttering the code with tons of ids. However, it is rarely needed to have an id on every element especially if you just work with svg.js because it will create ids if needed
