### ISSUE TITLE
Uncaught TypeError: Object function Array() { [native code] } has no method 'from' -> svg.min.js:2

### ISSUE THREAD

**Issue by coolmatt** [svgdotjs/svg.js#1122]
Hi,

This happens with an old Chrome (31.0.1650.63)... any chance it'll be fixed ?

Thanks
matt.

**Comment by Fuzzyma** [comment]
Try to include the polyfills from the dist folder or try the current master. But generally spoken old browsers are not supported because our target browsers are specified as

```
    "last 1 version",
    "> 0.25%",
    "not maintained node versions",
    "not dead"
```

You can look up what that means on browserslist.

However, you can just build svg.js yourself with your own targets which will then have the polyfills you need
