### ISSUE TITLE
Typescript declarations don't match up with documentation

### ISSUE THREAD

**Issue by remty5** [svgdotjs/svg.js#1138]
In the Typescript declarations file, the `animate()` function under the `Runner` class is set to require a duration, whereas [the documentation](https://svgjs.com/docs/3.0/animating/#animate) example shows chaining `animate()` without durations.

Edit: Actually, there's a lot that's wrong with the declarations, dmove() doesn't exist under the Runner type, you can't use an object in animate() under the Runner class, and probably others

**Comment by Fuzzyma** [comment]
As a surprise the documentation is actually right here because the duration is optional. Feel free to file a PR to solve it.
And whenever you find something, feel free to raise issues and/or create PRs. Unfortunately I have only so much time left to work on svg.js and rely on help from others whenever possible
