### ISSUE TITLE
Getting the coordinates of a click event

### ISSUE THREAD

**Issue by erelsgl** [svgdotjs/svg.js#128]
Thanks a lot for this excellent library! I created this simple application with draggable points: http://tora.us.fm/math/graphics/svgdisjointrects.html and I want to enable the user to add new points by clicking on the page.

I managed to add a click event to the SVG paper with:

```
draw.click(function(event) {
   console.dir(event);
})
```

But, I haven't found the x-y coordinates of the click point in the click event. I found clientX and clientY, but they seem to be relative to the client window, not to the SVG paper...

**Comment by KMax** [comment]
How it should be used in 2.6.3 version of svg.js?

I use svg.js from angular.js 4.4.4 and this code works for me (resulted x,y are as expected), but i'm not sure that it's a correct way:

```
draw.click(function(event) {
   var x = event.layerX - draw.parent().offsetLeft
    ,  y = event.layerY
})
```

The `draw.parent().offsetTop` is not used, because it returns unexpected (or incorrect) value. E.g. `115` instead of `0`.
