### ISSUE TITLE
Text alignment differs between 3.0 and 3.1

### ISSUE THREAD

**Issue by johanjeppsson** [svgdotjs/svg.js#1302]
I've been trying to align some text with percentage coordinates, but have run into some issues. I've done something like this
```javascript
  var draw = SVG().addTo("body").size("100%", "100%")
  
  draw.rect("30%", "100%").fill('#3a3')
  draw.text(function(add) {
	  add.tspan("Bold").attr("font-weight", "bold")
	  add.tspan("text").newLine()
  }).move("15%", "40%").font({anchor: "middle"})
```

where I expect the text to be centered in the green rectangle for the x axis. I couldn't get it to work with the latest release, but if I go back to a 3.0 release, I get a behavior more in line with what I expect.
[3.1.2 fiddle](https://jsfiddle.net/8h0zy157/7/)
![Screenshot 2023-06-08 20 33 39](https://github.com/svgdotjs/svg.js/assets/20884523/caf77d32-6be6-4896-b76c-5e4f303aa3ee)
[3.0.10 fiddle](https://jsfiddle.net/8h0zy157/6/)
![Screenshot 2023-06-08 20 40 47](https://github.com/svgdotjs/svg.js/assets/20884523/d1226107-cff6-493e-b1ef-97ae3e26a976)

Am I doing something wrong, or is this a bug?

**Comment by Fuzzyma** [comment]
In order to position text by it supper left corner, svg.js does some number juggling internally. The older version used even more juggling to make percentage values somehow possible. However, we decided to not do that in 3.1.2. Instead, if you only want to set a literal value for x and y you can use `amove` which is the same as just setting the values via `attr`. 
So just replace move with amove and you are good to go
