### ISSUE TITLE
Getting the bbox of text

### ISSUE THREAD

**Issue by eric-g-97477** [svgdotjs/svg.js#1323]
# Bug report

I asked the question on SO: [How can I draw text using SVG.js?](https://stackoverflow.com/questions/78774133/how-can-i-draw-text-using-svg-js)

```
I am trying to figure out how to use SVG.js to draw text. In
my attempt below, the text is being created and drawn, but
only a few dots show up. This must be part of the text being
drawn, but it is being clipped. I am not sure why this
clipping is happening or how to fix it.

My end goal is to create an SVG with text fitted inside some
geometry. To do this, I need to measure the text first so I
can compute the geometry dimensions. Therefore, it is
important to me to create the SVG object before adding the
SVG to a DOM element.

For the code below, what do I need to do so the text show up
correctly?
```

And received the following interesting response:

```
Also: calling bbox on an element which is not in the Dom yet
will yield one of the following:

an error
wrong results
correct results but but an overhead

That's because the browser can only calculate the bounding
box for elements that have been rendered. Svg.js tries to
get around that by attaching the element to the Dom
temporarily but that can yield to wrong results and produces
an overhead.
```

Assuming this is accurate...

I am not sure if there is something more that can be done so the correct results can always be produced...

**Comment by Fuzzyma** [comment]
It was me who answered your question.
I have to say that while I appreciate that you asked on stackoverflow first, reporting it again even tho the author answered you there feels kinda disrespectful of my time.

It also seems like you didn't try what I suggested in the response and instead asked for working code.
Usually people will try helping as much as possible but expect that the person asking is also putting effort into finding the solution.
There is plenty of documentation out there that shows you have to render text. And I even stated what you need to do in order to achieve what you want (=visible text).

Therefore I am closing this and will refer back to stackoverflow

**Comment by eric-g-97477** [comment]
I'm sorry you feel that way. StackOverflow works best when complete, working solutions are provided.

I had no idea you already answered me on SO and thought you would like to know about the defect in your library which I hope you can fix at some point.
