### ISSUE TITLE
Running error ，when add  array prototype methods

### ISSUE THREAD

**Issue by zfjhui** [svgdotjs/svg.js#1326]
When add  array prototype methods
![image](https://github.com/user-attachments/assets/9a591b3c-381a-47cf-ba29-962b55a0e5cc)
![image](https://github.com/user-attachments/assets/554f9cc3-ada3-47a1-b0d0-2a28134feb0f)
![image](https://github.com/user-attachments/assets/acc62da5-f880-471e-ae5c-9272f493aa8c)
![image](https://github.com/user-attachments/assets/3474bd87-2ff1-427d-8716-4a9eaf0baf4b)

**Comment by Fuzzyma** [comment]
Extending the prototype of buildin objects is frowned upon and shouldn't be done for exactly the reason you show here (any many more).

If you need extra methods on your array, extend the base array class and use your extended array:

```js
class MyArray extends Array {
  get first() { return this[0] }
}
```

The error happens, because you created readonly properties on the array prototype.
I WANT to overwrite some array methods so I cant skip the ones that already exist.

So I am sorry, but this wont be fixed
