### ISSUE TITLE
PathArray always absolute?

### ISSUE THREAD

**Issue by peteruithoven** [svgdotjs/svg.js#233]
When I'm reading through the documentation the array property of a path element should return the segment's of it's pathdata. It also states that it returns it with the original command types: 

> Original syntax is M0 0 or m0 0. The svg.js syntax ['M',0,0] or ['m',0,0].

But when I use it it always seems to return the absolute versions, it transforms m into M and translates it's values into absolute values. 
This is confirmed by the source: 
https://github.com/wout/svg.js/blob/1286e3de26baa3d75ec6a6eafbb2eaa11305c2e1/src/patharray.js#L137

It's not really a problem for me, it just feels like the documentation is confusing or wrong.

**Comment by villanus** [comment]
I know this is a closed and old issue, but what is the best way to scale (increase size, or decrease size) of a path?   

I am trying to avoid nesting SVGs since Adobe Illustrator does not support them (the goal is to create art which illustrator can read). 

Moving works.  Is there a a method for scale?

**Comment by Fuzzyma** [comment]
Despite the fact, that this is the wrong topic for this issue and you should use Stackoverflow for plain questions:

Have a look here: https://github.com/wout/svg.js#size
And here: https://github.com/wout/svg.js#scale

If you want plain a plain svg without any nested svg or groups find this: https://github.com/wout/svg.js#ungroup--flatten
