### ISSUE TITLE
size() calculates NaN when bbox width is zero

### ISSUE THREAD

**Issue by albohlabs** [svgdotjs/svg.js#505]
I've got a polyline with two points and same x-coordinate.

<img width="517" alt="bildschirmfoto 2016-07-07 um 13 11 39" src="https://cloud.githubusercontent.com/assets/163665/16651480/6423a2e2-4444-11e6-86a1-6bb79ada9169.png">

On resizing the svg element, the `ResizeHandler.resize.event.calc` triggers the  `size` method which calculates `NaN` for the new x. 

<img width="624" alt="bildschirmfoto 2016-07-07 um 13 25 11" src="https://cloud.githubusercontent.com/assets/163665/16651737/42ab0d56-4446-11e6-814f-84bab2331f7e.png">

This would be fixed if there is minimal width of 1px. This could be checked perhaps in the `bbox` method. What do you think?

**Comment by Fuzzyma** [comment]
Its totally fine for a shape to have a width or height of zero. But we have to make sure, that we check for it and don't produce something like division by zero.
Thanks for reporting!

**Comment by Fuzzyma** [comment]
@albohlabs what do you think is the expected behavior when caling lines:

- only scale the possible value (height in your case) and let width untouched
- add half of the width to every point so taht the new line is centered in the size-box you provided

Would be great to have your thoughts about that

**Comment by albohlabs** [comment]
I would also prefer the first one.
