### ISSUE TITLE
Someone is parallel publishing svg.js

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svg.js#541]
Interestingly someone is parallel publishing svg.js under https://www.npmjs.com/package/svgjs but is a few versions behind. Do you (@wout) know why [ar7](https://www.npmjs.com/~ar7) and @ch3sn3k is motivated to do this?

From @wout:
Hmm, didn’t know about that.
This is his statement:

>The .js breaks es6 imports so I need to republish it…

Is this really the case?

From @dotnetcarpenter:
Well, yes an no. svg.js is not modular enough that you can import part of it. e.g. I can not `import poly from "src/poly"` since it assumes that `SVG.invent`, `SVG.extend` and `SVG.Shape` is already defined but offer no path to where it's defined.

No browsers currently implements es6 modules but rollup can package modules defined with import/export as well as removing dead code. Other current options are babel and traceur.

That being said, I have downloaded the svgjs version and I see nothing that implies that any work has been done to enable this kind of import. `import SVG from "dist/svg.js"` should work in all current transpilers. This will import the entire library, same as doing `<script src="dist/svg.js"></script>`. It seems that https://www.npmjs.com/package/svgjs is just a slow mirror of https://www.npmjs.com/package/svg.js. We could ask them to transfer ownership to our new svgdotjs organization. I have talked with the npm people before in a similar case with https://www.npmjs.com/package/traits.js where we got the package name transferred to the traits.js organization.

**Comment by ch3sn3k** [comment]
Hello everyone,
I am using SVG.JS library for several years, my current build system of my project is based on the browserify and npm. I would like to have all the dependencies version over NPM. Thus I was looking for the solution for your library. 
The first google result was the https://www.npmjs.com/package/svgjs. During this summer I need to upgrade your library in my project and I find out that the "svgjs" is using old version, so I contact  [ar7](https://www.npmjs.com/~ar7) to ask if he is going to upgrade library. He told me that the repository served only for his small project and he is no longer using it. So he transferred the rights to me. 
Later I find out that you are publishing the package in your repository. So I just switched my project to yours one and leave the svgjs unupgraded. Today I just add @wout  as a collaborator to the [svgjs]https://www.npmjs.com/package/svgjs) repo. So you can change it as you like.

**Comment by wout** [comment]
@ch3ns3k Thanks! Can you add @dotnetcarpenter as well?

**Comment by ch3sn3k** [comment]
Done

**Comment by dotnetCarpenter** [comment]
@ch3sn3k thanks!
Since [svgjs](https://www.npmjs.com/package/svgjs) has hundreds of downloads a month, I think we should either publish to both URLs or ask npm to redirect to a canonical URL. I'll ask the npm guys what their usual resolution is.

**Comment by dotnetCarpenter** [comment]
In the short run I can update https://www.npmjs.com/package/svgjs with our current release. I'll post the npm answer here

**Comment by dotnetCarpenter** [comment]
From NPM:

>Hi Jon,
>
>Thanks for reaching out. We wouldn't redirect the URL, but you could either continue publishing to both package names or deprecate the one that you do not wish folks to use: https://docs.npmjs.com/cli/deprecate, and in the deprecation message let people know to use the svg.js package name.
>
>Let me know if you have any questions about this,
>Kiera

The way I currently publish to the two end points is by first do `npm publish` and then change the `name` field in `package.json` to `svgjs`, save and then `npm publish` again.

It's not a lot of work but I still think that deprecation will save us some trouble in the future. As far as I understand, the svgjs package name can never be taken by another package. So confusion should be minimum.

**Comment by wout** [comment]
Sounds good!

**Comment by dotnetCarpenter** [comment]
https://www.npmjs.com/package/svgjs is deprecated with the following message: *Moved to svg.js! Please use: npm install svg.js   For more information please see: https://github.com/svgdotjs/svg.js/issues/541*

**Comment by metaa** [comment]
@dotnetCarpenter:
You only deprecated two versions (see image). Please deprecate all of them, including [`svg.js`](https://www.npmjs.com/package/svg.js) which seems to be superseeded by the namespaced version by now.

This can be very confusing for people finding those old packages.

![image](https://user-images.githubusercontent.com/5056880/54948429-e7f90700-4f3c-11e9-815c-771e87ed5300.png)

**Comment by Fuzzyma** [comment]
Svg.js is not deprecated. These are all valid versions. We only depreciate versions which should not be used anymore because of mistakes we made such as a broken api or something like that.
We moved to an org because it is simpler for us as a team to manage our versions. That doesn't mean that the old versions are not supported anymore

**Comment by metaa** [comment]
So you're telling me that you're fine with having three almost identical packages based on the same file history under these names:
* https://www.npmjs.com/package/svgjs
* https://www.npmjs.com/package/svg.js
* https://www.npmjs.com/package/@svgdotjs/svg.js

which just **confuses** people finding this because it's not clear at all which of those is the "right" one (`svgjs` even points to installing `svg.js`, wtf) and do not want to give clear information about the weird branching across these three packages?

That's the most ignorant, idiotic and careless thing I've seen today. I'm outta here.

**Comment by saivan** [comment]
You'll want to watch your language, I've gone ahead and reported this. 
We don't tolerate any kinds of insults here and those kinds of comments are way out of line.

To address your questions. 
- We document clearly in our README.md, the correct and expected way to install svgjs. We have just started distributing via an npm organisation because it makes it easier for our users
- There are three versions because the first one was pushed years ago (and is not maintained by us, it was a user submission which we don't control), the second was the one we used up until very recently and the organisation is where we will host all of our new versions.
