### ISSUE TITLE
animation.at() can not read the property 'duration' after the animation is finish;

### ISSUE THREAD

**Issue by semi-xi** [svgdotjs/svg.js#554]
like the example 

```js
var draw = SVG('drawing').size(1000, 1000);
    var rect = draw.rect(100, 100).move(50, 50)
    var animation = rect.animate({
        duration:1000,
        ease:'>'
    }).move(200, 200)
    document.onmousemove = function(event) {
        animation.at(event.clientX / 1000)
    }
```

before the animation finish,whatever you move your mouse ,the animation can be move to a current position.but,if the animation is finish,when you move your mouse ,it will throw a error like ` Uncaught TypeError: Cannot read property 'duration' of null(…)`

**Comment by Fuzzyma** [comment]
Well when the animation is over, the animation is over. It looks like you dont want to animate something but just move it according to your mouse. Animations are cleaned up after finishing thats why its not accessible anymore...
You can use `pause()` to stop the timer so that your animation never stops. But that kinda doenst hit the underlying problem.

What is your exact usecase? How do you want the code to behave?

**Comment by semi-xi** [comment]
@Fuzzyma  ok i know

**Comment by Foxhunt** [comment]
Hi,

bit old issue but relevant to my usecase.

I want to "search" through a set of animations with a slider element.
The slider has a min of 0 and a max of 1000
```javascript
function animate(at) {
  lineAnims.forEach(a => a.at(at))
  circleAnims.forEach(a => a.at(at))
  rotations.forEach(a => a.at(at))
}

document.getElementById('slider').oninput = (event) => {
  let val = event.target.value / 1001
  console.log(val)
  animate(val)
}
```
When i divide by 1000 i can't go back in time as soon as i hit the end of the slider.
I understand that this is working as intended because animations are cleaned up after finishing.
I worked around that by never getting to 1 in my val calculation and using 1000s instead of 100s to have it still look like its at 1.

Is there another way to do it?

full code [here](https://github.com/Foxhunt/svg-animation-test)
