### ISSUE TITLE
Cannot set `stroke-width` without setting `stroke`

### ISSUE THREAD

**Issue by burnpanck** [svgdotjs/svg.js#560]
... which is a problem if one wants to set the `stroke` via CSS, but not `stroke-width`.
If I read the source correctly, this happens in the `attr`-setter: When `stroke-width` is set, the `stroke` attribute is set to the cached value `_stroke`, unless the width is zero. According to a comment, this is done as a bug-fix against browsers that do render a stroke even if the width is zero. However, in the case no stroke has been set, this will actually apply the SVG.js default stroke as an inline style.

**Comment by burnpanck** [comment]
Ok, the workaround is easy, just call `attr('stroke',null)` after setting `stroke-width`, but nonetheless, this is unexpected.

**Comment by wout** [comment]
This is a browser issue. SVG.js already tries to work around it:

https://github.com/svgdotjs/svg.js/blob/master/src/attr.js#L32-L35

**Comment by Fuzzyma** [comment]
@wout I think this is a different problem. the op found, that setting a stroke-width on an element will trigger a stroke on the element whether you want it or not. Thats because svgjs always adds stroke.

Maybe we should remove the browser workaround. User should know about that browserbug  and always make sure they set stroke somewhere

**Comment by burnpanck** [comment]
@Fuzzyma Exactly!

**Comment by wout** [comment]
Agreed. Is this for 2.5 or 3.0?

**Comment by Fuzzyma** [comment]
I guess it's better to put it into 3.0

**Comment by Fuzzyma** [comment]
Closing this as solved in the [3.0 branch](https://github.com/svgdotjs/svg.js/tree/3.0.0)
