### ISSUE TITLE
Missing signature/property in TS typing

### ISSUE THREAD

**Issue by albohlabs** [svgdotjs/svg.js#564]
```SVG('drawing')``` function call produces the following error:

```
error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "svg.js"' has no compatible call signatures.
```

The ```SVG.Matrix``` access results into another error message:

```
error TS2339: Property 'Matrix' does not exist on type 'typeof "svg.js"'.
```

**Comment by albohlabs** [comment]
Import the lib via ```import * as SVG from 'svg.js'```.

@rdfriedl Do you have any idea what i'm doing wrong?

**Comment by Fuzzyma** [comment]
The most likely thing is that you are doing everything right but the signature is wrong. We are missing the knowhow to keep this up to date. Feel free to file a pull request to fix those issues!

**Comment by rdfriedl** [comment]
If the typescript modules work anything like ES6 modules, then i have a good idea of whats going on.

If you do `import * as <some name> from "<some lib>"` then it takes all the exports from the library and dumps them into an object.
Though since svg.js is not written in ES6 or typescript there is only one export, the `SVG()` function.
So when you do `import * as SVG from "svg.js"` you get something that looks like this
`{ SVG: SVG() // main SVG function }`

Again if the typescript modules work the same as ES6 then the correct way to import it would be `import SVG from "svg.js"`

Hope that helps
`

**Comment by albohlabs** [comment]
Thanks for you help.
I adapt the export declaration from [lodash](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/index.d.ts#L239), [angular](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/angular/index.d.ts#L17) and the [module template](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) and this works fine with both imports.

See PR #565 for more infos.
