### ISSUE TITLE
Version mismatch in banners under `dist/*`

### ISSUE THREAD

**Issue by Zearin** [svgdotjs/svg.js#573]
The files under `dist/` have comments that describe their version.  

Looks like they both have `2.3.7` listed as their version, although `{component,package}.json` list `2.4.0` for the version instead.

**Comment by Zearin** [comment]
Same goes for the files hosted at the CDN (!!!)

**Comment by Fuzzyma** [comment]
Looks like someone failed to run gulp before tagging the new version :). Thanks for the headup. This will be fixed with the next release.

**Comment by Zearin** [comment]
Yay! :)  

(And thanks for the speedy response!)

**Comment by dotnetCarpenter** [comment]
Probably my bad, although I'm sure I did a new build for each release. @Fuzzyma we might need to check if our gulpfile is still correct.

**Comment by dotnetCarpenter** [comment]
Ahh. Now I know. It's because I used `npm version` to tag the releases and that function requires everything to be committed before changing version number. So if you want to commit our dist folder and use `npm version` then you will commit our dist with the old version number and then `npm version` will change the version.

Note to self: **DON'T USE `NPM VERSION`** (especially since we also frown upon having a `v` in the release name)
