### ISSUE TITLE
Ability to add `<style>` element?

### ISSUE THREAD

**Issue by Zearin** [svgdotjs/svg.js#579]
One of the best parts of SVG is the syntax crossover with HTML+CSS.  And `<style>` is one of the best parts of that!

I looked around the docs, then the code, and could not find a built-in way to add `<style>` to an `<svg>` element.

Can you add this feature in the next release?

**Comment by wout** [comment]
You can use `SVG.Bare` to achieve that:

https://svgdotjs.github.io/elements/bare/

Something along the lines of:

```javascript
draw.element('style').words('rect { fill: #f06; }')
```

Here's an example:

https://jsfiddle.net/wout/ajxqo2d8/

**Comment by Zearin** [comment]
@wout Thank you.  :)  That is an acceptable workaround.  

But shouldn’t `<style>` be part of the core library?  Can I put in a feature request for it?

**Comment by wout** [comment]
I know, acceptable isn't good enough :)
Let's continue this conversation in #517.

**Comment by Zearin** [comment]
> I know, acceptable isn't good enough :)

Acceptable is acceptable! :)  It’s just that it’s a workaround, since the other SVG elements get a dedicated class to instantiate them.

See you in #517.

**Comment by Fuzzyma** [comment]
You can write an extension to add what you need.
I am pretty sure I already answered this question on stackoverflow giving
an incomplete implementation of said extension. Maybe you find it. I will
search when I have some time left

Am 05.02.2017 18:54 schrieb "Zearin" <notifications@github.com>:

@wout <https://github.com/wout> Thank you. :) That is an acceptable
workaround.

But shouldn’t <style> be part of the core library? Can I put in a feature
request for it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/svgdotjs/svg.js/issues/579#issuecomment-277536174>, or mute
the thread

**Comment by dotnetCarpenter** [comment]
I think we're not the far from each other when I say that we want to keep SVG.js as small as possible and offer features through plugins.
But we really need to work on our plugins.

1. I suggest we select some *core* plugins that we unit test and maintain in the same manner as we maintain SVG.js.
2. That we include this features in the normal documentation. E.i. include the following doc under [Path](https://svgdotjs.github.io/elements/path/?q=path)
```js
// create path
var path = draw.path('M150 0 L75 200 L225 200 Z')

// animate path
path.animate().plot('M100 0 H190 V90 H100 Z')
```
and say that [svg.pathmorphing.js](https://github.com/Fuzzyma/svg.pathmorphing.js) needs to be included. svg.pathmorphing.js should live in our svgdotjs organization before it is a *blissed* plugin, so all SVG.js maintainers are able to fix bugs.
3. Make sure that SVG.js is proper modularized. That is, `shape.js` should be able to work without `gradient.js` (thought example). An obvious way to implement this is via [ES2015 modules](http://www.2ality.com/2017/01/babel-esm-spec-mode.html). So that you can create a build with the plugins and core you need. When modules finally land in browsers (perhaps 2018), then the build process will be handled by the browser on-the-fly.

**Comment by Fuzzyma** [comment]
Is is planned to have a plugin section on the page anyway where it is shown how powerful those plugins are. We could link to this section whenever there is a plugin mentioned in the docs.

**Comment by wout** [comment]
@dotnetCarpenter I agree. The library is already too bloated. Initially I aimed to stay under 10k gzipped. Now, we're at 16k. So if we can offload parts to plugins, BETTER!

**Comment by Fuzzyma** [comment]
Closing this in favour of #517
