### ISSUE TITLE
Allow the method font to be used like the method attr

### ISSUE THREAD

**Issue by RmiTtro** [svgdotjs/svg.js#620]
I think it could be good for consistency to allow the method `font` to be used like the method `attr`. This would make the following call possible:

```javascript
text.font('family',   'Helvetica') // setter of 1 attribute
text.font('leading') // getter
```

**Comment by Fuzzyma** [comment]
Haha now you can set the leading of the text in 5 fashions:
```js
text.leading(1.5)
text.attr({leading: 1.5)
text.attr('leading', 1.5)
text.font({leading: 1.5)
text.font('leading', 1.5)
```
I like the idea anyway :).
@wout @dotnetCarpenter your thoughts?

**Comment by Fuzzyma** [comment]
I tried an implementation vzt I dont know if I like it:

```js
function(a, v) {
    var ret = {}, k
    
    if (typeof a == 'object') {
      for (k in a) {
        ret[k] = this.font(k, a[k])
      }
      return v ? ret : this
    }

    return a == 'leading' ?
        this.leading(v) :
      a == 'anchor' ?
        this.attr('text-anchor', v) :
      a == 'size' || a == 'family' || a == 'weight' || a == 'stretch' || a == 'variant' || a == 'style' ?
        this.attr('font-'+ a, v) :
        this.attr(a, v)
  }
```

What do you guys think?

**Comment by RmiTtro** [comment]
This seem good to me. The only change I would propose is to replace
```javascript 
a == 'size' || a == 'family' || a == 'weight' || a == 'stretch' || a == 'variant' || a == 'style'`
```

by

```javascript 
['size', 'family', 'weight','stretch','variant','style'].indexOf(a) > -1
```

**Comment by wout** [comment]
Be careful with indexOf. Although it might look prettier it's very slow. That's why I wrote it that way because performance wise it's the best option.

**Comment by Fuzzyma** [comment]
Yes I needed to learn it the hard way when I wrote the path parser. Comparison is always faster - even with lots of possibilities

**Comment by wout** [comment]
Yeah :)
And not just a little bit: https://jsperf.com/indexof-vs-value-is/1

This is where I learned a lot about JS performance:
http://javascriptrocks.com/

I am thinking about testing performance a while now. That's why I wrote this one a while ago:
https://github.com/svgdotjs/svg.js/blob/master/bench/svg.bench.js.

We are thoroughly testing our code with Jasmine, which is great, but we fail to test our code on performance. So surprises like #613 pop up out of the blue.

My priority list while writing SVG.js has always been:
1. Performance
2. Size
3. Code aesthetics

So, I would like to propose the introduction of more benchmarks. At the moment I'm fighting with a deadline but I can make some time in two weeks. If you guys have any suggestions...

**Comment by Fuzzyma** [comment]
@wout haha atm I just want to take a look at #626 because it blocks me from developing 3.0 any further :P. But I dont want to endanger your deadline, though...

**Comment by Fuzzyma** [comment]
Since there is no voice against that implementation I will add i so we can ship it with the 2.5 release. Its coming closer ;)

**Comment by RmiTtro** [comment]
Wow it really is much slower... Now I feel dump for proposing it :man_facepalming:. It make you wonder what JavaScript do with its array for the performance difference to be this big. Thanks for your link @wout, I will definitely need to take a look!

I'm all for more benchmark, now that we have nearly 100% code coverage thanks to @Fuzzyma I think that is the next step.

**Comment by Fuzzyma** [comment]
The 100% code coverage is a lie :D. Well not in general but in many cases. Code is executed because it's used by other function we test and not because we have a test for the specific line. I saw that at many places and this could hide errors away. However it's not Easy to see which lines are "semi-covered"
