### ISSUE TITLE
Extend the EventTarget Class with methods for event handling

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#641]
Just to be consistent I would like to replace the loaded callback on `SVG.Image` with a loaded event.

**Comment by Fuzzyma** [comment]
I agree with that. In the fx module we use events, too but kept the during()/after() method for not breaking the api. Maybe we could remove this methods, too?

**Comment by wout** [comment]
Yes, we should remove them everywhere.

**Comment by Fuzzyma** [comment]
The problem with events is, that they are awfully slow and that they only can be dispatched on nodes.
In the new fx module we dont have a node to dispatch. And creating a detached node only for dispatching events on it is highly memory intensive and leads to lots of garbage collections.

So my proposal is the following:

- extend the EventEmitter class with the following methods:
  - `addEventListener`
  - `removeEventListener`
  - `getEventDispatcher`
  - `dispatchEvent`

This class should be completely able to remove and add events on its own.
However in case of SVG.Shapes we HAVE a node which we want to use. In that case `getEventDispatcher` returns a node and not `this` so that the events are bound and dispatched on the node instead of the object.

**Comment by Fuzzyma** [comment]
This landed in 3.0 with 47fda3cf67cdc8ab20d3b1ba9d65a810adddf5ee in the following way:

`EventTarget` is a class that all classes can extend to get event handling.
It comes with the following interface:

- `on()` bind the event
- `off()` unbind event
- `dispatch()` dispatch an event on the object and return the event
- `fire()` same as dispatch but returns the object

When you need to use a special event target (e.g. a node), you need to implement the following methods:
- `getEventTarget()` returns the target
- `getEventHolder()` returns the object on which the elements are saved

Additionally the target needs to implement:
- `addEventListener()`
- `removeEventListener()` and
- `dispatchEvent()`

The default is the EventTarget itself
