### ISSUE TITLE
Changes to SVG.Set

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#645]
### Precis
`SVG.Set` is incomplete and outdated and it is not consistently returned throughout the library. It should be either updated or removed.

### Problem
1. `SVG.Set` is missing some methods like `text()` to name one, but there are many more
2. The `inherit()` method is a bad approach
3. Members are not easily accessible (`set[3]` for example; should always go through `set.get(3)`)

### Proposal
- [ ] Remove the `inherit()` concept altogether
- [ ] Make `each()` accept a key/value pair (e.g. `set.each('fill', '#f06')` or `set.each('attr', 'fill', '#f06')`)
- [ ] Remove the internal `members` array and store members in indecis directly on the object
- [ ] Make `length` a property instead of a method (more array-like)
- [ ] Add the `collect()` method for collecting attributes (e.g. `set.collect('fill')` or `set.collect(function() { return this.toHex() })`; may be called `map()` too
- [ ] Return, where possible, an instance of `SVG.Set` rather than an array
- [ ] Add `toArray()` method to convert set to an array (or use `valueOf()` for that purpose)

**Comment by Fuzzyma** [comment]
And `remove` should remove by index and not by element because you could have one element twice in a set

**Comment by saivan** [comment]
Then adding something like map would also make sense.

**Comment by saivan** [comment]
If a user intends to use a set, they could just use our list like this:

```
let list = // output from some SVG.js Function
let set = new Set(...list)
```

**Comment by wout** [comment]
@Fuzzyma What are the scenarios for having the same element twice in a `Set`?

**Comment by Fuzzyma** [comment]
I often used set more as an array (I could have used an array instead) and added elements to it myself with `add()`. Nobody stops you from adding one element two times.

I had a talk with saivan yesterday and he mentioned, that he really likes the old set beside its flaws.
It really costs to overcome that - but maybe we should let it have its old syntax...

Then we would just improve it by:

 - calling SVG.Set.inherit only once at the very end of the dist file. This we can get rid of it in the extend method which is a huge plus. Downside: Plugins need to call it themselves.
- adding the features discussed above (index access, each-improvement...)
- rename it to SVG.List to make intention more clear.

I am REALLY not a fan of the inherit code. Put people seems to really like it. And I understand thats easier to write

```js
set.animate(200,200).move(200,200)
```

instead of

```js
set.each('animate', 200, 200).each('move', 200, 200)
```

and in the end I know no better solution

**Comment by saivan** [comment]
We could avoid plugins calling it themselves by just modifying extend after the creation of the library so that it calls the necessary methods :)

**Comment by Fuzzyma** [comment]
You mean overwrite extend with a new version? Iam not a fan of that idea :D. It sounds like a hack.
