### ISSUE TITLE
Need plugin update to follow 'strict mode' restrictions

### ISSUE THREAD

**Issue by xlinbsd** [svgdotjs/svg.js#660]
Hello,

_Using svg.js from npm in a meteor project._
I'm not sure my problem is general, but since v2.52 with 'strict mode' control,
I need to update manually the filter extension for accessing ```SVG```, with a ```require```

Example in svg.filter.js
```
;(function() {
  var SVG = require('svgjs');
  // Main filter class
  SVG.Filter = SVG.invent({
[...]
```

I assume the problem is also true for other plugins.

Regards

**Comment by RmiTtro** [comment]
This seem a lot like issue #659. I don't think this issue is caused by strict mode but more by a change made in 016720aec2b7d52be19f91151370617aaaa91709. More precisely, this change:

```javascript
// Before
var SVG = this.SVG = function(element) {

// Now
var SVG = function(element) {
```

Basically, this cause `SVG` to not be put on `window` (be a global variable) when used as a commonjs module (and maybe amd but I don't know it enough to be certain). And I'm pretty sure most of the plugins we have will be affected by this issue since most of them expect `SVG` to be a global variable.

That leave us with 2 options. 

### Option 1
We put back the `this.SVG =` which should prevent any more users to have this issue (already two) and is the one that require less work.

### Option 2 
We fix all of our plugins so they work correctly when used as commonjs module. This option will require more work but is the one that would make more sense since the whole point of commonjs is to not have to use global variable anymore. I think I could make those fix to the plugins, I would just replace grunt by webpack which have settings to do this kind of stuff relatively easily. 

What do you think @wout, @dotnetCarpenter and @Fuzzyma?

**Comment by Fuzzyma** [comment]
I am not sure why people even think that modules could work like that. I never ever thought about requiring something without passing the result to a variable. I also never saw a tutorial for that. So I wonder why people do that. 
That's why I am all for option 2. How many of our plugins have a require? I can't think of one.

**Comment by wout** [comment]
+1 for option 2. I think it makes sense.

**Comment by xlinbsd** [comment]
Hello,
@Fuzzyma 
I'm not sure to use correctly the modules. I'm not a js ninja.

I imported svgjs and svg.filter.js with ```meteor npm install --save svgjs svg.filter.js```
Then I add the following lines in my project js
```
import SVG from 'svgjs'
import filter from 'svg.filter.js'
```
Did I do wrong ?

**Comment by Fuzzyma** [comment]
The `import` way is not supported with svg.js as far as I know. We support requirejs and commonjs so I don't know how Es6 syntax has to be used. 

Am I missing something?

**Comment by xlinbsd** [comment]
@Fuzzyma 
My mistake, ```import``` is converted to ```require``` syntax by meteor, so it is probably not a problem.
[meteor doc about import and insert](https://guide.meteor.com/structure.html#using-require)

**Comment by Fuzzyma** [comment]
@xlinbsd is there a way to tell meteor, that it should not convert it to `require(...)` but `var something = require(...)`?

**Comment by xlinbsd** [comment]
It's exacty what I tried
```var SVG = require('svgjs')```
instead of
```import SVG from 'svgjs'```
the behavior is the same, I need to change the ```svg.filter.js``` to help him find the ```SVG``` object in my project

**Comment by Fuzzyma** [comment]
Well then this is a not intended breaking change and should be inverted. We should reapply it in 3.0 then. 

Do you all agree?

**Comment by dotnetCarpenter** [comment]
We should do option 1. Reinstate this.SVG =
The reason I removed it is, that the UMD itself can not be in "strict mode"
when "this" is "undefined". In this case it is define to be the global (in
a browser that is window), in sloppy mode. I had a discussion with @fuzzyma
about this and he did not like "strict mode" in the UMD, so we removed it.
Since we did that, we are in sloppy mode" and can have "this.SVG =".

Less fuzz and it works for everyone.

I am unable to do anything the next 2 days so feel free to do the change.

**Comment by RmiTtro** [comment]
The problem @xlinbsd is having is really with the svg.filter.js plugin that should do a `require('svg.js')` when used as a commonjs module. The "professional" way to fix this issue would be to add a umd wrapper to all of our plugins which would handle this kind of stuff (a bit like what we have for svg.js with the difference that it would also need to handle the svg.js dependency). We can re add the SVG global but I think it kind of goes against the whole point of using commonjs in the first place. That being said, as thing are now, none of our plugins are working with svg.js 2.5.3. So, I guess we should re-had the global at least until we have sorted our plugins out.

**Comment by Fuzzyma** [comment]
@RmiTtro I agree with you, that the correct way of solving this would be to change our plugins. But as a matter of fact: We broke code of our users and that should never happen except its a major version change.
So we are kinda forced to revert this change.

@xlinbsd did you also try omiting the `var` keyword and go `SVG = require('svgjs')`? That would add SVG to the global namespace again and the modules might be able to find SVG again

**Comment by xlinbsd** [comment]
@Fuzzyma  I trid the global ```SVG``` and reset my ```filter``` plugin change. Unfortunately that do not work.

**Comment by Fuzzyma** [comment]
mh ok was worth a try...
@dotnetCarpenter it seems that the `this` **does** conflict with strict. So we have go back to sloppy mode and make this a thing for 3.0

**Comment by RmiTtro** [comment]
I'm surprised that ommiting the var keyword didn't work...

**Comment by Fuzzyma** [comment]
I reverted the changes and published them with 2.6. Please doublecheck if everything is working correctly again.

**Comment by xlinbsd** [comment]
@RmiTtro I modified the header of the first svg component loaded to
```
// import SVG from 'svgjs'
SVG = require('svgjs')
import filter from 'svg.filter.js'
```
And then obtain the following error in the js console
```
Uncaught ReferenceError: SVG is not defined
```

The error stack leads to the first plugin SVG call
```
SVG.Filter = SVG.invent({ 
```

**Comment by Fuzzyma** [comment]
@xlinbsd albeit its fixed now another test: Did you try loading the plugin with `require`, too? They might be encapsulated differently when loaded with `require`

**Comment by RmiTtro** [comment]
Don't know if it will change anything, but could you also try

```javascript
SVG = require('svg.js')
```

**Comment by RmiTtro** [comment]
Oups, formating didn't work, what I meant in my previous message is could
you try this:

SVG = require('svg.js')

Le 21 avr. 2017 7:05 AM, "Rémi Tétreault" <tetreault.remi@gmail.com> a
écrit :

> Don't know if it will change anything, but could you also try
>
> ```javascript
> SVG = require('svg.js')
> ```
>
> Le 21 avr. 2017 6:56 AM, "Ulrich-Matthias Schäfer" <

**Comment by xlinbsd** [comment]
2.6.0 work well with plugin resets and my standard ```import``` statements ! Thanks

@RmiTtro && @Fuzzyma Are you asking me to try formatting on 2.6.0 or 2.5.3 version ?

**Comment by Fuzzyma** [comment]
2.5.3 - we want to understand the issue better :)

**Comment by xlinbsd** [comment]
I found a way. I deleted all imports of all components and only added the following header on my main svg template
```
SVG = require('svgjs')
filter = require('svg.filter.js')
```
with ```var SVG``` that do not work (expectedly).

**Comment by Fuzzyma** [comment]
OK that's what I expected - good to know after all

**Comment by xlinbsd** [comment]
Do you need me to try other things or should I close the issue now since the 2.6.0 release is OK from my point of view  ?

**Comment by Fuzzyma** [comment]
We can close this. Thanks for your help!

**Comment by xlinbsd** [comment]
Thank you for your help !
