### ISSUE TITLE
Cannot move text properly after rotating

### ISSUE THREAD

**Issue by SimoneMSR** [svgdotjs/svg.js#685]
I would like to animate a line of text:
1) rotate the line for 90°
2) let the 2^ half of the line move away from the first half

I have tried to do that in this [fiddle](https://jsfiddle.net/simone_msr/vzm9s08g/9/), but I faced with this issues:
1) why do I have to add that strange 5 constant for Y position?
2) why, when I introduce a second animation after rotating, this 5 constant becomes insufficient?
3) why the second animation applied directly to text does not work (in the second drawing, the apple) but works when applied to a group (the pear) ?

**Comment by Fuzzyma** [comment]
Thats another question for stackoverflow...

Your fiddle is not really stripped down to the minimum required code. I cant really figure out what it is doing.

Here is a working fiddle: https://jsfiddle.net/w77468qu/

I guess your issue arises from the way text is handled in svg.js. When you set an y with move or y it will try to fit the left upper edge of the text to that coordinate (like any other shape). However, text is normally placed by its baseline. So svg.js changes coordinates a bit so that it fits.

By using attr(y, ...) instead of move you get more control and as you can see in my example: a smooth animation.

For your other questions: As I said, I cant figure out what the code is supposed to to
