### ISSUE TITLE
Script at End of Body

### ISSUE THREAD

**Issue by beauremus** [svgdotjs/svg.js#712]
This is more of an observation than an issue.
I should have known better, but I initially included the JavaScript calling SVG in the head of my HTML. This fails. I began troubleshooting using different load events. I eventually figured out that it ran fine when I included my JavaScript at the end of the body instead of the head. I don't recall seeing this anywhere in the documentation.
Not a big deal but could save future developers a little headache if examples show this explicitly.

**Comment by Fuzzyma** [comment]
You can't use the Dom before the Dom is not (at least partially) loaded. This is an old known thing in Javascript development. 
I don't know if it's worth to add it to documentation. 
@dotnetcarpenter what do you think?

**Comment by dotnetCarpenter** [comment]
I think, since more and more front end developers are using frameworks like Ractive, Polymer or just are used to wrap their scripts in `$(document).ready(() => {...})` when using jQuery... I mean, with these many abstraction from *real* front end development, it is probably a surprise to many that you can not manipulate the DOM before the HTML is actually parsed by the browser - **in short**, yes we should add it to the documentation.

I'll open an issue in [https://github.com/svgdotjs/svgdotjs.github.io](https://github.com/svgdotjs/svgdotjs.github.io/issues)
