### ISSUE TITLE
Timing: at() not working

### ISSUE THREAD

**Issue by sebaranowski** [svgdotjs/svg.js#746]
Seems lite the `at()` function is broken. I tried the documented example code like can be seen here: http://jsfiddle.net/wmtt8rkz/175/
```
Uncaught TypeError: Cannot read property 'duration' of null
```

**Comment by Fuzzyma** [comment]
Thats because the `=` method was removed by accident when the fx module was reworked. However reimplementing it introduced a huge performance drop. So we freezed this feature for now.

We need to update the docs on this.

However to achieve teh same result try this: http://jsfiddle.net/wmtt8rkz/176/

**Comment by sebaranowski** [comment]
Wow, many thanks for the quick reply! Great guy - have a nice weekend :)

**Comment by Fuzzyma** [comment]
Thanks! You too
