### ISSUE TITLE
Missing textflow plugin

### ISSUE THREAD

**Issue by jbeard4** [svgdotjs/svg.js#84]
There appears to be a page up referencing a textflow plugin: http://svgjs.com/textflow/

It links to a missing github repository: https://github.com/wout/svg.textflow.js

This seems like it would be a useful plugin. Is there a reason it was taken down?

**Comment by ccann** [comment]
Any chance you still want to make svg.fromhtml.js available? :-)

**Comment by Fuzzyma** [comment]
What is this fromhtml.js plugin?

**Comment by ccann** [comment]
This was in reference to the above comment from like 5 years ago:
> Now I use a html element to define the textflow. I wrote a plugin (svg.fromhtml.js) that converts html to svg. It works very fast and adds the benefit of inline styles as well, without ever having to create a text element in svg.

**Comment by Fuzzyma** [comment]
jep - I wasnt around at this point. So if you know what this plugin was supposed to do I might help

**Comment by ccann** [comment]
All I know is what I read in this thread, that it could potentially help with converting HTML text to SVG text including newlines, line-wrapping, etc. Sounded useful, apologies for resurrecting an old thread and derailing you :-)

**Comment by Fuzzyma** [comment]
Unfortunately its not as easy as it sounds to tame svg text. While there are possibilties to wrap lines by length, you will never get the exact look and feel as html text because the browser does not give any metrics for the used fonts.
The plugin was never finished unfortunately.
The approach is basically measuring the text length and break lines when they get to long. I implemented an approach to do that some time ago but I am not allowed to share it here unfortunately.

**Comment by ccann** [comment]
well, thanks for jumping in anyway, appreciate the quick response!
