### ISSUE TITLE
how to animate path attribute d

### ISSUE THREAD

**Issue by binggege** [svgdotjs/svg.js#847]
API: http://svgjs.com/elements/#path-plot one argument
code: https://github.com/svgdotjs/svg.js/blob/master/dist/svg.js#L2165 need 4 arguments

my pathData change:

``` json
    {
        "id": "30",
        "layerId": "lively_icon_47",
        "propertyName": "plot",
        "startTime": 0,
        "endTime": 300,
        "interpolator": "LINEAR",
        "type": "path",
        "fromValue": "M 832 512 L 192 896 L 192 128 L 832 512 Z M 832 512",
        "toValue":   "M 832 800 L 192 896 L 192 128 L 832 800 Z M 832 800"
    }
```
```
code-1: 
path.animate(3000).plot("M 832 800 L 192 896 L 192 128 L 832 800 Z M 832 800")
result-1:
<path id="lively_icon_47" d="M0 0" name="path_1"></path>

code-2:
path.attr({d: "M 832 800 L 192 896 L 192 128 L 832 800 Z M 832 800"});
result-2:
<path id="lively_icon_47" d="NaN 832 800 NaN 192 896 NaN 192 128 NaN 832 800 NaN NaN 832 800" name="path_1"></path>
```

**Comment by saivan** [comment]
Did you see this? https://github.com/otm/svg.path.js

**Comment by Fuzzyma** [comment]
Take a look at #845. Seems like there is a bug to fix. You can use that branch temporally

**Comment by RmiTtro** [comment]
Hi @binggege, I just pushed a commit on master that should fix the issue with using `.attr()` to animate the d attribute of a path.

As for your question, there is 2 ways to modify the d attribute of a path. You can use the `plot` method or the `attr` method. The difference between the 2 is that when you use `plot` the path string is converted into a `PathArray` object and is cached whereas the `attr` method just modify the d attribute of the underlying node without performing any conversion. You can run into problems if you mix the use of those 2 methods. For example, if you set the d attribute using the `attr` method and then try to read the value using the `plot` method you won't get the value you just set. That is because the cached PathArray is not modified when you use the `attr` method. So you should either just use the `plot` method or the `attr` method.

Personally, I think you should use the `plot` method since that is the method we expect the users of this lib to use to modify the d attribute of a path.

Also, with the fix I committed, you shouldn't need to use `svg.pathmorphing.js`. This plugin  is useful when you want to morph to a path that use different commands which is not your case if I look at your example.

**Comment by uebusaito** [comment]
little demonstration will be very helpful for beginners like me. 
I am very confused how to use this on my svg path element.

**Comment by Fuzzyma** [comment]
Its pretty straight forward. You do it like any animation in svg.js

```js
var path = canvas.path('M0 0 L20 20').fill('none').stroke('black')

path.animate().plot('M0 0 L20 50')
```
