### ISSUE TITLE
Repeated points in polygon

### ISSUE THREAD

**Issue by amitguptagwl** [svgdotjs/svg.js#864]
When I create a polygon using `draw()` it inserts some points 2 times. Eg When I create a polygon with 4 points

```html
<polygon id="SvgjsPolygon1063" points="179,177 179,177 397,147 323,381 323,381 88,350 88,350" class="labelbox shape"></polygon>
``` 

If I delete repeated points manually from the element I see there is no difference in the shape. But if I move or reshape the polygon it again inserts 7 points.

In case of 3 points (triangle) polygon, total points are 5.
In case of 4 points polygon, total points are 7.
In case of 5 points polygon, total points are 8.

It'll be helpful if you can explain the logic so I can persist unique points and restore them properly.

**Comment by Fuzzyma** [comment]
That never happend to me. I honestly would rather believe that your mouse is broken and sometimes sends 2 clicks instead of that beeing a library issue :D 

Can you doublecheck on the demo page? When the issue is there, too. Then its your mouse. If not, the trouble is most likely in your usage of this library in which case your code might be required ti pin down the issue. However in that case its a question for stackoverflow anyway :)

**Comment by amitguptagwl** [comment]
It's a good guess :D but not doubt it can happen. I'll double check with 2 other mouses I have.

**Comment by amitguptagwl** [comment]
The same mouse working fine on demo page. So it means, I'm not handling the event very well. Thanks for your suggestion.

**Comment by amitguptagwl** [comment]
For the visitors who face the same problem, here is the [SO question](https://stackoverflow.com/questions/50668727/repeated-points-in-polygon-when-using-svg-draw-js?noredirect=1#comment88534299_50668727) answering the problem.

Issue 

I was calling `draw()` when I create the element, on `mousedown` event, and on `mouseup` event. It works fine with other shape like rect, circle but not with polygon.

Solution

I've removed `draw()` to create element, and put a condition in `mousedown` event.
