### ISSUE TITLE
Save SVG as image

### ISSUE THREAD

**Issue by amitguptagwl** [svgdotjs/svg.js#869]
I've created an [application](https://funcards.github.io/match-it) which generate playing cards (div) having transformed images. I've to save all the cards as image. I tried html2canvas but it failed. 

I was wondering if I use svg.js to draw images and convert card into SVG. Is it possible to save SVG as image using this library? 

> I couldn't find anything on net. so asking here

**Comment by Fuzzyma** [comment]
As I said multiple times now this type of questions are for stackoverflow.com. Besides that a simple. Google search for "svg to image" gives you solutions already

**Comment by amitguptagwl** [comment]
>As I said multiple times now this type of questions are for stackoverflow.com.

@Fuzzyma Sorry to make you a bit angry. But such questions don't fit under stackoverflow guidelines as well. So there is a high chance to get it closed there same as happened here.

>Besides that a simple. Google search for "svg to image" gives you solutions already

Yes, there are many options and libraries available to export SVG as image file. My question was particularly related to this library.

Thanks for your very quick reply. :)

**Comment by tdelov** [comment]
I've been doing quite a bit of searching on google and stack overflow.
There are indeed many conversions available, however, the problem lies with how the other libraries, commands or scripts will render the svg elements and images compare to how svg.js does it.
For what I was trying to do, which included embedded images and other svg files, the only thing I found that comes close to rendering the svg files in a similar manner to svgjs is inkscape. 

I was pretty surprised to find no export functionality.

**Comment by SteveGZr** [comment]
I have used rsvg to rasterize the svg.

`rsvg-convert -o <output_file> -w <width> -h <height> <source_file>`

I had to replace html special characters because rsvg can't handle them.
I also had to remove unnecessary empty tspans because rsvg uses the dx and dy attributes of empty tspan elements, which is wrong.
Everything else is working fine.
