### ISSUE TITLE
Matrix is not invertible when trying to scale up from 0

### ISSUE THREAD

**Issue by razvanioan** [svgdotjs/svg.js#898]
# Bug report

## Fiddle

https://jsfiddle.net/razvanioan/2e15kjbq/2/
https://codepen.io/qdev/pen/MqWxrZ?editors=1010

## Explanation

- if element is scaled to 0 (x or y), it cannot be scaled back up (animated or not)
- console error on Safari: `Matrix is not invertible`
- console error on Firefox: `InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable` (inside inverse() method)
- for the moment I will scale to something very close to 0, in order to make it work (eg: 0.000001)

**Comment by Fuzzyma** [comment]
When you scale something to zero you lost all information about the transformation if the object. You created a zero-matrix. You cannot go back from this. This is a limitation by math so we cannot solve it.
You can try to save the matrix before you scale it to zero and reuse it when you scale up again. I dont see any other way

**Comment by saivan** [comment]
There is an easy way to fix this. Just scale to an epsilon instead of zero. This isn't a bug though, as @Fuzzyma pointed out. But what you could do is `el.scale( yourScale + eps )`. Where eps is just some really small number, I like to use something like `1e-6`. So what you did is correct :) 

But yes, if you had an element where: its matrix was `matrix(1, 2, 3, 4, 0, 0)`. when you write `el.scale(0)`, you are applying the matrix `matrix(0, 0, 0, 0, 0, 0)`. Which basically loses any information that you may have had about the directions that were applied before. 

So when you try to scale it back up, anything times zero is still zero.
I appreciate the bug report though :)
Great to have you on board!

I'll go ahead and close this soon if you don't have any follow-up queries?

**Comment by saivan** [comment]
If you have any further questions, feel free to write back :)
