### ISSUE TITLE
Clip Path allows <g> elements erroneously

### ISSUE THREAD

**Issue by RoastVeg** [svgdotjs/svg.js#904]
# Bug report

The `SVG.ClipPath` class currently allows elements of the type <g> to be added to it. Although these elements are permitted for masks, they have no formal specification in any current SVG standard, and different browsers and programs behave differently when loading them. Other elements exist beside <g> which have no defined place in a Clip Path in the SVG standard.

## Fiddle

[This fiddle](https://jsfiddle.net/s06mfv5u/62/) contains a short example of the behaviour. On Chrome (and likely most browsers), the path is simply ignored and no content is shown. This does not make for straightforward debugging.

## Explanation

- What is the behaviour you expect?

An exception is thrown when the element is added to the path

- What is happening instead?

The element is added without a warning that it will not behave as intended

- What error message are you getting?

None

**Comment by saivan** [comment]
So we had a bit of a discussion about this one, and the spec is here - look under the allowed elements section:

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath

You raise a very valid point, clipPaths shouldn't be allowed to have group elements on them - this is not allowed according to the svg spec. However, the problem is, adding checks for every possible error that a user could make will greatly slow down the library.

However; I do agree that better documentation would be in order here. We should at least document the fact that the user should be careful about what they add to a clip path. However, after speaking about this, we think it would be better not to throw random exceptions. 

A user may have legitimate reasons for adding a group to a clip path, even if it might be ignored in the drawing.

**Comment by saivan** [comment]
However, to fix your example this code works:

```js

var canvas = SVG('canvas')

// create your example here
var group = canvas.group()
var clip = canvas.clip()
var rect = group.rect(100, 100).move(100, 100).fill('blue')

clip.add(rect.clone())
group.clipWith(clip)

```
