### ISSUE TITLE
move() does not work when using units

### ISSUE THREAD

**Issue by ensonic** [svgdotjs/svg.js#906]
# Bug report

## Fiddle

https://jsfiddle.net/ensonic/e8hvcx9u/

## Explanation

Issue #678 claims that units are supported and don't need to be documented (cool, units are in the standard anyway). I'd expect to be able to express everything with units (millimeter in my case). Unfortunately I get:
```
Error: <circle> attribute cx: Expected length, "10mm2.5mm".
```

**Comment by ensonic** [comment]
It is in the fiddle:
```
var draw = SVG('canvas')

var led = draw.defs().circle("5mm").stroke('#f00').fill('none')

var g = draw.group().move("10mm", "10mm")
g.add(led.clone(g).move("10mm", "10mm"))
```

**Comment by Fuzzyma** [comment]
mh thats odd... that should work. Have to check that one

**Comment by ensonic** [comment]
Would these need to use number.js?
https://github.com/svgdotjs/svg.js/blob/HEAD/src/element.js#L32

**Comment by Fuzzyma** [comment]
Well yes, the cx and cy methods (for rectangulat shapes) and the x and y methods (for circle like shapes) are computed values. We use the bbox to know where to place the shape. However, the bbox is in px only and you cannot calculate mm out of that. So units are supported for all native attributes but not for the sugar svg.js adds because it relies on the bounding boxes.

we thought about adding expoer modifiers which would make your idea possible. Atm its a bit more tricky because you need to loops through all children by yourself.

If you use mm for all of your units it might be easier to just use a viewbox in mm and stay with the unitless values inside the svg
