### ISSUE TITLE
Document tree functions not working when adding a title element to a rectangle

### ISSUE THREAD

**Issue by vitorcoder** [svgdotjs/svg.js#909]
I'm trying to create a title element as a rectlangle's child using the Bare element creation function along with put, add, addTo and putIn functions, but the code breaks.

Ex:
```
var canvas = SVG('canvas').size(500, 500);

var rect = canvas.rect(100, 100).fill('black');
rect.attr({x: 250, y: 250});
		
var title = canvas.element('title').words('A tooltip!');
title.putIn(rect);
```

The errors are usually something like "Uncaught TypeError: parent.add is not a function"

I was a able to reproduce the problem in this fiddle:  [https://jsfiddle.net/29utw6qr/3/](https://jsfiddle.net/29utw6qr/3/)

**Comment by Fuzzyma** [comment]
rect is not part of the comtainer class and therefore has no child-management-methods. I see that this is a limitation because it has to be possible to add descriptive elements to rect and other shapes.

We definitely need to rethink that part. Unfortunately there is no easy fix to allow rects to add childs so this bug will most likely get fixed in 3.0 only

**Comment by vitorcoder** [comment]
Thanks for the feedback, I'll try some workaround.

**Comment by Fuzzyma** [comment]
@vitorcoder you might want to try the 3.0 branch. Every class has dom capibilities there so your eample code should just work there.

Even this is possible:

```js
rect.add('<title>A tooltip!</title>')
```

**Comment by Fuzzyma** [comment]
3.0 was released and this issue is fixed there
