### ISSUE TITLE
Group x() and y() don't correctly reference the top-left

### ISSUE THREAD

**Issue by offbynull** [svgdotjs/svg.js#943]
# Bug report

## Fiddle

http://jsfiddle.net/offbynull/k4g2xbhz/

## Explanation

The behavior of groups is nothing like what people expect. move(), x(), and y() aren't getting/setting the top-left corner of the group and bbox() doesn't include translations.

In the fiddle, the first button will use the built-in move() to move the group to (100,100). Notice how the top-left corner isn't at (100,100) -- it's slightly offset. The second button will actually move the top-left to (100,100).

**Comment by Fuzzyma** [comment]
Thanks for the bug report. The move command of groups is implemented as simple translation. When you call x of the group you simply get back transform('x'). We decided to not do any magic with combining transform and bbox here.
bbox always only returns the untransformed box of an element. Thats how it is defined. In 2.x we added gbox which actually was bbox with added translation.

In the end its a matter of how you define it. I agree, that x should always return the value equal to bbox.x because thats what valid for all elements (so x() returns an untransformed value). However when you use `x()` as setter, its not so easy anymore. Setting x should act like you would set bbox.x (thats only locical because x() and bbox.x always match. But you cannot do that for groups. Well, technically you could move all elements in the group so the bbox changes the way you want. Actually that is maybe the cleanest solution. However, we didnt do it here. Instead we translate the box when setting an x. And because we do that, x() also returns only the translationX of the group.

**Comment by Fuzzyma** [comment]
We decided to follow the best route in v3.0. So your poblems shoulnt exist in version 3 anymore. 
Group is now moxing consistently. Actually all content of the group is moved.

If you have any further questions, feel free to post!
