### ISSUE TITLE
Animating Text

### ISSUE THREAD

**Issue by Coolseb** [svgdotjs/svg.js#953]
Hi, I'm learning to use SVG.js and I think I've encountered a bug.

I'm struggling to use SVG text. I managed to display text statically.
[http://villars.pro/img/Screen-1.jpg](url)

But trying to achieve a simple falling letters animation, you can notice the 'error' :
The text has changed place on the screen, and 1 letter (i) has been misplaced.
[http://villars.pro/img/Screen-2.jpg](url)

In order to achieve the falling letter by letter effect, I placed every letter in a tspan node inside a SVG text node (all with SVG.js functions)
Then I use a basic animate function which produces the 'buggy' effect.

Any guess on what might be the issue ?

**Comment by Coolseb** [comment]
I use 2.7.1
I'm building the fiddle now

**Comment by Coolseb** [comment]
maybe that will suffice (my code is quite plain)

I have a main SVG container (var named ctnr below) that holds all visible content in which the text node is created.

code to add the text node
`let txt = ctnr.text('').fill('white').font({
                family : 'arial',
                size : 100,
                anchor : 'middle',
                weight : 'bold',
            });`

code to add the letters in a tspan
`txt.build(true);
            for(i=0; i<string.length; i+=1){
                txt.tspan(string[i]);
}`

code to animate the letters
`for(i=0,len=txt.node.childNodes.length; i<len; i+=1){
                const node = SVG.adopt(txt.node.children[i]);
                node.animate(1000,'backOut',i*50).y(middleOfViewport);
            }`

BTW : i tried to use txt.children() but it fails

There's really nothing more to it

**Comment by Coolseb** [comment]
https://jsfiddle.net/hs6xby0c/2/

I hope i do this the right way.
In the fiddle, the animation won't start

**Comment by Coolseb** [comment]
sorry newer version https://jsfiddle.net/hs6xby0c/3/

**Comment by Fuzzyma** [comment]
Jep - realized that. I see the bug and I looked into the generated code. And the generated code is totally fine. Nothing unexpected there. So I really dont get where this gap is coming from.

Even more strange: The behavior is consistent across browsers. And when you place them directly without animation the result is the same (except the ! which moves a tiny bit which is another thing which shouldnt happen).

BUUUUT: I just changed the text-anchor to start and the bug is gone: https://jsfiddle.net/Fuzzy/2v13touL/

At this point I would consider it a browser bug because the generated code is fine as far as I can tell

**Comment by Coolseb** [comment]
Thank you,
I can definitely live with this solution.
I've been fighting with this for days looking for a solution, I wouldn't have thought of that.

**Comment by Fuzzyma** [comment]
Me neither. I am kinda confused that this happens. It seems like browsers dont calculate tspan position correctly when the text-anchor is not start. You can even open your dev tools and hover the tspans. Not even the dev tools show the correct bounding box for the letters. Really strange.
You might want to open a bug report at mozilla and chrome.

I will consider this as "can be closed" since we cannot really change that behavior

**Comment by Coolseb** [comment]
Thx a lot for the swift answers :)
