### ISSUE TITLE
Version 2.7.1: The `center()` function does not work as expected

### ISSUE THREAD

**Issue by Perlkonig** [svgdotjs/svg.js#959]
# Bug report

According to the docs, the `center()` function is supposed to "Move the element by its center to a given cx and cy position," and it gives the following example: `rect.center(150, 150)`. But it doesn't appear to actually do this.

Here's a jsfiddle showing the problem:

https://jsfiddle.net/Perlkonig/mvbzy97p/

Here's the code if you don't want to spend the click:

```javascript
var draw = SVG("drawing");
var rect = draw.defs().rect(50, 50).fill("red");
draw.use(rect).center(25,25);
var point = draw.circle(5).move(25,25).fill("black");
```

You'll see that the top-left corner moves to 25,25 and not the center. Is this some weird thing with `use()`? Any guidance appreciated.

**Comment by Perlkonig** [comment]
I just looked at the source code. All it does is call the `cx()` and `cy()` functions, which doesn't work on elements like `rect`s. Given the description in the docs, I was assuming this function actually did something more—that it actually worked on any `element`.

**Comment by Fuzzyma** [comment]
It does. The cx and cy functions work different for rects and circles. See here: https://jsfiddle.net/Fuzzy/Lrsgb8c7/1/

As I wrote on stackoverflow already, the use element has issues with bounding boxes which are different from what you expect. Just get the bounding box of the use element and draw it and you will see what I mean

**Comment by Perlkonig** [comment]
I apologize, but I'm just not following.

https://jsfiddle.net/Perlkonig/mvbzy97p/40/

The bounding box appears to be identical to the rect.

**Comment by Fuzzyma** [comment]
Ok, it is indeed a bug. And I thought it was an issue with the bbox behavior of use...
The `width` function is not implemented for `use`. Instead the default one is used which just pulls the `width` attr and thats never set on a use element and therefore defaults to 0.

For a quick fix try the following before your code:

```js

SVG.extend(SVG.Use, {
    width: function () {
        return this.bbox().width
    }
}
```

Please note that this width function only implements the getter because you cannot really set the width of a use element without changing the element which is referenced.
I dont know if changing the referenced element is desirable because if the element is referenced anywhere else it will change there, too. However, to stay consistent I might implement this behavior.

**Comment by Perlkonig** [comment]
Had to jump through a hoop to make it work in TypeScript, but that appears to fix the problem. Thank you for your patience.
