### ISSUE TITLE
find doesn't work with 'use' tag sub elements (version 3)

### ISSUE THREAD

**Issue by clodprogea** [svgdotjs/svg.js#965]
this is the fiddle : 

https://jsfiddle.net/zkqst2d8/

there is a sub element added with the 'use' tag

find works finding the 'ContentControl' element, then it fails finding the sub element 'Element0'.
Debugging the code find finds the sub element 'use' but it can't traverse the sub element

jquery $('Element0') works

**Comment by Fuzzyma** [comment]
no, `$('Element0')` does not work as well as `$(ContentControl)` does not work. These are ids in your code not tag names. So please use a hashtag (`#`) in front of the id because thats how jquery (and `find`) works.

That said, the group with the id Element0 is not even a child of the Element with the id `ContentControl`.

**Your code is not even valid HTML/SVG**

**Comment by clodprogea** [comment]
yes, jquery works I miss typed describing the problem, of course jquery needs '#'

regarding Element0 is a child of the ContentControl, you can inspect the resulting tree DOM using your browser debugger as you can see in the following screenshot :

https://www.screencast.com/t/8KjYWDsYW4

**Comment by Fuzzyma** [comment]
No, what you see is a shadow root. You cannot access these with jquery. Ofc you can access `$('#Element0')` because its somewhere in your dom. Find will find that instance too - but NOT below ContentControl.

**Comment by clodprogea** [comment]
ok
