### ISSUE TITLE
How to delay the animation in 3.0

### ISSUE THREAD

**Issue by junedchhipa** [svgdotjs/svg.js#973]
To delay the animation, I used the following params in v2.7

```javascript
el.plot(path).animate(speed, easing, delay)
```

In v3.0, it seems like the 3rd argument (when) doesn't accept numbers. What should I pass here to delay animation with specific milliseconds?

Also, the `afterAll()` function doesn't work in 3.0. Is there an alternative?

Sorry, if it is already in the docs and if I missed it.

Thanks a lot!

**Comment by Fuzzyma** [comment]
The function signature for `animate` in v3 is

```js
el.animate(duration, delay, when)
```

`when` can be `now, absolut, relative, after`. The default is `after` which means the animation starts after the last one (if there was one, otherwise it starts `now`).

All animations in v3 are managed by Runners that are scheduled on a timeline. To execute a function after every runner is finished, you want to listen for the finish-callback of the timeline.

I answered a question on stackoverflow which gives a brief overview on how to use the timeline:
https://stackoverflow.com/questions/54762861/how-can-i-use-timelines-in-version-svg-js-3-x/54783645#54783645
