### ISSUE TITLE
Wrong width and height only with the exported svg code

### ISSUE THREAD

**Issue by mixalistzikas** [svgdotjs/svg.js#977]
# Bug report

If you try the following fiddle you will see that everything is ok with the created badge. If you inspect the html code you will see the following part

`<pattern id="SvgjsPattern1013" x="0" y="0" width="100" height="120" patternUnits="userSpaceOnUse"><image id="SvgjsImage1012" xlink:href="https://cdn-images-1.medium.com/max/800/0*rTlC4udP5uqgpA6F" width="100" height="120"></image></pattern>`

where width = 100 and height = 120

The problem is with the exported svg code. Check the console... The width and height are zero!!!
I have to change it manually to work.

## Fiddle

[Demo fiddle](https://jsfiddle.net/j7yd4Lr9/1/)

**Comment by Fuzzyma** [comment]
You call export before the image is even loaded. The size of the pattern is set as soon as svg.js knows the dimensions of the image. But it only knows that, when the image is finished loading. Ofc you see the correct values when you inspect it because at that point the image IS loaded. But the call to export comes too early
