### ISSUE TITLE
Modification of paths

### ISSUE THREAD

**Issue by JanMisker** [svgdotjs/svg.js#988]
Not sure how to bring this to your attention, so I do it here as a feature request + proposed solution.

I wanted to be able to simplify paths. I found a couple of resources (mainly https://github.com/mourner/simplify-js) how to do it, but not yet within the svg.js ecosystem. 

So I made a plugin: https://github.com/JanMisker/svg.pathmod.js

I'm sure there are issues with the packaging, but the code works ok. I would be happy to publish to npm on its own name, but perhaps you want it under @svgdotjs/ ?

**Comment by Fuzzyma** [comment]
Thats a though question. Ofc its good for the user to have all plugins under one org. However, it also means, that the svg.js team maintains this plugins and we simply cannot maintain all community plugins.
Thats why I actually would propose to publish it on your own.

I looked into the code of the plugin and arent sure what it is doing. It seems to simplify line-paths (so basically polygons^^). We already have a plugin called toPoly() which creates a polygon out of any path but it seems to work differently.

One more thing I saw is, that you used a function to "absolutize" your path. Since you get your paths from svg.js you dont need to do that because svg.js is doing that already.
Furthermore you might want to start with version 1 and not version 3 :D.
The dependency to svg.js should be 3.0.12 minimum. Every version before has quite a few bugs.

I like how you used rollup to integrate the plugin into the ecosystem :)

**Comment by JanMisker** [comment]
Cool, I published it as svg.pathmod.js on npm.
Also added an example of what it does, see here: https://janmisker.github.io/svg.pathmod.js/

**Comment by Fuzzyma** [comment]
Wow, these examples make it really clear! Nice work!

**Comment by Fuzzyma** [comment]
Btw is there a reason why you don't allow polygons / lines as inputs?

**Comment by JanMisker** [comment]
No reason, just started out with paths because that's my use case for now. But indeed, extending also polygons and polylines would definitely work.

**Comment by saivan** [comment]
Would be cool to extend this to work with bezier paths as well haha - not sure if that already works, but I cant see it :P

**Comment by JanMisker** [comment]
For those interested, I made a simple shape editor using svg.js, in the context of an online audio editor for kids. It allows you to draw shapes as a step in the thinking process of making audio for a movie, as a visual score. Something I really like is that it allows you to edit (complex) shapes using 'control points', see the white dots in the image below on the turquoise shape.

If I find time I will try to publish some of the components into their own open repository, or propose ways to integrate it, perhaps with svg.draw.js.

See it in action here (Chrome only): https://app.watchthatsound.nl/#movie=WTS-Bit_001/view=visualscore/lang=en 

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/334008/59998851-c48b4880-9660-11e9-9a6f-fec18235c98d.png">
