### ISSUE TITLE
svg.js 3.0 with svgdom has no root in Node.js

### ISSUE THREAD

**Issue by michael-brade** [svgdotjs/svg.js#990]
# Bug report

## Fiddle

I have no fiddle because this does work in the browser. Only Node.js is affected.
Here is the code:

```js
const { SVG, registerWindow } = require('@svgdotjs/svg.js')

if (global.window === undefined) {
    global.window = require('svgdom')
    global.document = window.document
    registerWindow(window, document)
}

const span = document.createElement("span")

const canvas = SVG().addTo(span)

console.log(canvas.root())    // null

canvas.clip()                 // crash

console.log(span.outerHTML)
```

## Explanation

The above code works in the browser. In Node.js, the `span` element should also be the root.
Instead, it crashes with:
```
node_modules/@svgdotjs/svg.js/dist/svg.node.js:6360
    if (!this.isRoot()) return this.root().defs();
                                          ^

TypeError: Cannot read property 'defs' of null
    at Svg.defs (node_modules/@svgdotjs/svg.js/dist/svg.node.js:6360:43)
    at Svg.<anonymous> (node_modules/@svgdotjs/svg.js/dist/svg.node.js:6698:19)
    at Svg.clip (node_modules/@svgdotjs/svg.js/dist/svg.node.js:296:17)
    at Object.<anonymous> (svg-test.js:15:8)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
```

I think the reason is that `svgdom` and `svg.js` both have a class called `SVGElement`, and `svg.js` thinks a root cannot be an `SVGElement`. But with `svgdom` the `span` inherits the `SVGElement`, in the browser it doesn't.

**Comment by Fuzzyma** [comment]
I think you have a mistake in your thinking. Every Dom has a root node. In html this is `<html>` but in svgdom, the root element is an `<svg>` element. You then use that svg element as root svg and build your canvas with it.
There is nothing like a span in svgdom. Their is pseudo support for html elements but per spec html is not allowed in an svg tag (exception here is the foreignElement).

In the Readme of svgdom it is written how to correctly setup an svg document with svg.js.

You just created a detached span node and tried to add a svg doc to it. I have no idea if that potentially works and if it does, it's not really how I expected it to be used. I think your code crashes because it cannot find the document in the parent chain (root() returned null). And obviously the clip method needs to find the root.

Actually that's an interesting case. I need to take a look here. I would have expected that isroot() returns true when the patent is null but I guess when I designed that I had something in mind not to do that...

**Comment by michael-brade** [comment]
Oh... interesting. I will have to take a look as well, I thought I can build a complete html document with svgdom - at least I have done that so far :-p

And yes, my assumption was wrong - there is no `SVGElement` in `svg.js`, you just check for that class in `Svg.isRoot()`. So forget about the last paragraph :-)

**Comment by Fuzzyma** [comment]
Jeah I guess a lot of people just start creating their own documents. I never intended that because in the browser a detached tree does nothing for you. But it seems like people like that svgdom works no matter if the nodes are detached or not.
Maybe we have to make it more robust in that habdsight.
You just have to keep in mind that svgdom will never have anything near full Dom functionality. Especially not for html elements!

**Comment by michael-brade** [comment]
Ah, now I don't know if I misunderstood or you did :-) I am using svgdom only if the code runs in Node.js - in the browser I don't need svgdom, svg.js is enough. But in Node.js I want to create a full html document with svg nodes included. It is irrelevant if the nodes are detached (I think..)

**Comment by Fuzzyma** [comment]
Yes there is no reason for svgdom in the browser. But when I developed I used the browser as blueprint for the behavior. And in the browser you always put your stuff into the Dom. Just creating a node and attaching another node to it doesn't give you a Dom. The Dom starts with the root element which is given to you by svgdom.
But people tend to think in another way when they use svgdom. They just build their detached tree.
It's an interesting usecase but I didn't intend it

**Comment by michael-brade** [comment]
I see, makes total sense. 

I think in my case it is about the order of creation: in the example above I did not create a Dom, but in LaTeX.js I do. However, I first build detached subtrees (because I don't know where they will be attached at the time of creation), and then at the end I build the Dom and attach the subtrees. Maybe we could account for that?

**Comment by Fuzzyma** [comment]
Yes that should be possible. It's strange though that your code works in the browser. Because that means that svgdom has a mistake somewhere.

My first thought was about a bug in svg.js but that actually makes no sense because it works in the browser.

I am short on time as always but I will try my best. In the meantime you can try to find the issue too

**Comment by Fuzzyma** [comment]
Your first guess seemed to be right. The Problem is created by checking for SVGElement in svg.js. And since ALL Elements in svgdom are SVGElement (even a span), the check fails. The root svg things it is not the root because it is in another SVGElement (the span) which is ofc nonesense.
I am not sure how to fix this bug fastest because we dont decide between html element and svgelement in svgdom.

As a quickfix for you: Just dont append the SVG you created to a span at start. Do it at the very end. That should resolve your issue.

**Comment by michael-brade** [comment]
Thank you very much, I came to the same conclusion, and I have no good suggestion of how to fix it yet. But your idea for a quickfix is perfect! It works :-)
