### ISSUE TITLE
Merging and manipulating PathArrays

### ISSUE THREAD

**Issue by valentinradu** [svgdotjs/svg.js#994]
@Fuzzyma It's me again :).  I'm trying to merge two path datas (e.g. `M 0 1L 1 1 ...` and `M 0 0L 1 1 ...`). I'm using `PathArray`s to store the data and merge them by simply concat'ing the arrays. This works good, however, I need to also manipulate the data before merging (e.g. translate, rotate, mirror), `PathArray` has `move` and `size` but that's about it. I was thinking a `transform` method would help and I'm ready to try and implement it, however I wanted to ask you beforehand:

1. Do you foresee any problem with this approach (I'd like it do be fully integrated, i. e. having the animations work as well)
2. Is there a better, easier way to achieve this?

**Comment by Fuzzyma** [comment]
This is something I do not count as a core functionality because something like this is rarely used.
When your paths only consists of paths, a transformation is super easy to implement. As you might know, there is the Point class which has a transform method. So you can simply do the following:

```js

pathArray.map(p => [p0].concat(new Point(p[1], p[2]).transform(...).toArray())

// or a bit more readable
pathArray.map(p => new Point(p[1], p[2])).map(el => el.transform(...))....
```

Ofc for your implementation you can just extend the pathArray with a transform method which does what you want. But for the moment I _think_ that we dont need it in the core

**Comment by valentinradu** [comment]
True, is super easy as it is. I'll close this issue. Thank you again!

**Comment by Fuzzyma** [comment]
I just realized that PointArrays have a transform method too. So there is no valid reason not to have it for PathArrays I guess. So if you are in the mood... :D
